
# Created on Thu Dec 18 13:00:23 2025

# author: 

# Nastavení cesty k souboru
file_path: 'data.xlsx'

# Časové omezení (formát RRRR-MM-DD HH:MM:SS)
# Můžete nechat prázdné nebo smazat, pokud omezení nechcete
date_from: '2025-12-31 00:00:00'
date_to: '2026-01-05 23:59:59'

sensor: ["9986", "8271", "0065", "0921"]
# Sampling frequency [Hz] (= 1/1825 seconds)
T_s: 1825
f_s: 0.000547945

# Nastavení os
axes:
  left_y:
      name: 'Teplota'
      marker: 'o'
      marker_size: 5
      line_width: 4
      label: 'Teplota [°C]'
      label_weight: 'bold'
      label_color: 'k'
  right_y: 
      name: 'Vlhkost'
      marker: 's'
      marker_size: 5
      line_width: 4
      label: 'Vlhkost [%]'
      label_color: 'k'
      label_weight: 'bold'
  x_axis: 
      name: 'Datum a čas'
      label_color: 'k'
      label_weight: 'bold'
      label: 'Datum a čas'
  
# Nastavení plotu
figure:
    fig_size: [12,8]
    font_size: 16
    tick_size: 16
    x_tick_rotation: 45
    title_size: 20
    title_weight: 'bold'
    legend_loc: 'upper center'
    legend_cols: 2
    legend_y_offset: -0.2
    color_palette: 'Set2'

# Nastavení ukládání grafů
save:
    on_off: True
    path: "vystupy/grafy"  # Složka pro export
    filename_prefix: "sensor_report"
    format: ['eps', 'png', 'pdf']
    dpi: 600
    transparent: True
        

