"""The off-site log: periods when a sensor was NOT measuring in the vineyard (MIGRATION_PLAN §2.8).

By default every sensor is assumed to measure in the vineyard. The owner keeps a hand-written
file, ``sensors/offsite_log.yaml``, with the periods when a sensor was elsewhere (office,
service, transport, storage). Quality control marks the samples of these periods
``PRE_DEPLOYMENT`` (:class:`~sivin.quality.checks.offsite.OffSiteCheck`) and the web portal draws
them as a grey band.

* :class:`OffSitePeriod` is one entry of the file: sensor, ``from``, ``to`` (``open`` or
  ``null`` while the sensor is still off site; a blank ``to:`` is an error), reason and note.
  Times are local wall-clock time (``YYYY-MM-DD HH:MM``, Europe/Prague by default) or ISO 8601
  with an explicit offset or ``Z``; they are stored in UTC. A local time that is ambiguous or
  does not exist because of a daylight-saving change is rejected with a request for an
  explicit offset.
* :class:`OffSiteLog` is the validated, immutable collection: known sensors only, no overlaps
  per sensor, at most one open period per sensor and it must be the last.
* :class:`OffSiteLogStore` reads the YAML file strictly (a duplicate key is an error, not "last
  one wins"); every error names the entry as ``entry #N`` (1-based) with its line and field, and
  says how to fix it. Times in messages are local time of the log's zone with UTC in brackets.

The JSON Schema ``sensors/offsite_log.schema.json`` is generated by :func:`render_json_schema`.
"""

from __future__ import annotations

import logging
import re
from collections.abc import Iterable, Iterator, Mapping, Sequence
from datetime import UTC, date, datetime
from itertools import pairwise
from pathlib import Path
from typing import Annotated, Any, Final, Literal, Self
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

import numpy as np
import numpy.typing as npt
import pandas as pd
import yaml
from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    PlainSerializer,
    PlainValidator,
    ValidationError,
    ValidationInfo,
    WithJsonSchema,
    field_serializer,
    field_validator,
    model_validator,
)

from sivin.core.defaults import DEFAULT_TIMEZONE
from sivin.core.ids import SERIAL_DIGITS, SensorId
from sivin.core.schema import MeasurementSeries
from sivin.registry.errors import AmbiguousSensorNameError, SensorLookupError
from sivin.registry.geojson import FILE_ENCODING, render_json
from sivin.registry.model import format_utc
from sivin.registry.registry import SensorRegistry

logger = logging.getLogger(__name__)

OffSiteReason = Literal["office", "service", "transport", "storage", "other"]
"""Why a sensor was not in the vineyard (the ``reason`` of an entry)."""

TIMEZONE_CONTEXT_KEY: Final = "timezone"
"""Key of the pydantic validation context that names the IANA zone of local times."""

TIME_TEXT_PATTERN: Final = (
    r"^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]{1,6})?)?"
    r"(?P<offset>Z|[+-][0-9]{2}:[0-9]{2})?$"
)
"""Accepted text of ``from`` / ``to``: local ``YYYY-MM-DD HH:MM[:SS]`` or the same with an offset.

Without ``offset`` the time is local wall-clock time of the log's zone; with ``Z`` or
``±HH:MM`` it is an absolute instant.
"""

_TIME_TEXT_REGEX: Final = re.compile(TIME_TEXT_PATTERN)

_JSON_TIME_PATTERN: Final = TIME_TEXT_PATTERN.replace("?P<offset>", "")
""":data:`TIME_TEXT_PATTERN` without the Python-only named group (for the JSON Schema)."""

ENTRIES_KEY: Final = "entries"
"""Top-level key of the log file: the list of entries."""

OPEN_END: Final = "open"
"""Value of ``to`` that marks a period that has not ended yet (``null`` is accepted too)."""

REGISTRY_FILE_NAME: Final = "sensors/sensors.geojson"
"""The sensor registry file, named in messages about unknown sensors."""

ENTRY_KEYS: Final = ("sensor", "from", "to", "reason", "note")
"""Keys of one entry, in file order."""

EXAMPLE_LINES: Final[Mapping[str, str]] = {
    "sensor": 'sensor: "77799986"',
    "from": 'from: "2026-03-01 08:00"',
    "to": f'to: "2026-03-05 16:00"   (or  to: {OPEN_END}  if the sensor is still off site)',
    "reason": "reason: service   (office, service, transport, storage or other)",
    "note": 'note: "battery replacement"',
}
"""One example line per key, shown when a key is missing."""

BLANK_HINTS: Final[Mapping[str, str]] = {
    "sensor": 'is empty - write the 8-digit serial in quotes, e.g. sensor: "77799986"',
    "from": 'is empty - write when the sensor left the vineyard, e.g. from: "2026-03-01 08:00"',
    "to": f"is empty - write a date/time, or '{OPEN_END}' if the sensor is still off site",
    "reason": "is empty - write office, service, transport, storage or other",
    "note": "is empty - write a note or delete the line",
}
"""What to do about a key written without a value (``to:`` and nothing after it)."""


class BlankValue:
    """A key written without a value in the YAML file (``to:``), as opposed to ``to: null``.

    Produced by :class:`OffSiteLogStore`'s loader; :class:`OffSitePeriod` rejects it with a hint
    from :data:`BLANK_HINTS`, so a half-filled entry never silently becomes an open period.
    """

    __slots__ = ()

    def __repr__(self) -> str:
        return "BlankValue()"


class OffSiteLogError(ValueError):
    """Raised when the off-site log cannot be read or violates a rule; names entry and field."""


class LocalTimeReader:
    """Read the time values of the log as UTC instants.

    Parameters
    ----------
    timezone : str
        IANA zone of local wall-clock times, e.g. ``"Europe/Prague"``.

    Raises
    ------
    ValueError
        If the zone is unknown.
    """

    __slots__ = ("_zone",)

    def __init__(self, timezone: str) -> None:
        try:
            self._zone = ZoneInfo(timezone)
        except (ZoneInfoNotFoundError, ValueError) as error:
            raise ValueError(f"unknown IANA time zone {timezone!r}") from error

    @property
    def timezone(self) -> str:
        """The IANA zone name."""
        return self._zone.key

    def read(self, value: object) -> datetime:
        """Convert one ``from`` / ``to`` value to an aware UTC datetime.

        Parameters
        ----------
        value : str or datetime.datetime
            Text matching :data:`TIME_TEXT_PATTERN`, or a datetime as produced by the YAML
            parser for an unquoted ``2025-12-17 12:00:00`` (naive = local wall-clock time).

        Returns
        -------
        datetime.datetime
            The instant in UTC.

        Raises
        ------
        ValueError
            If the value is not a time, has no time of day, or is a local time that is
            ambiguous or does not exist in the zone (daylight-saving change).
        """
        if isinstance(value, datetime):
            instant = value
        elif isinstance(value, date):
            raise ValueError(
                f"{value.isoformat()!r} has no time of day; write 'YYYY-MM-DD HH:MM', "
                f"e.g. '{value.isoformat()} 12:00'"
            )
        elif isinstance(value, str):
            instant = self._parse_text(value)
        else:
            raise ValueError(f"expected a time as text, got {type(value).__name__}")
        if instant.tzinfo is None:
            return self._local_to_utc(instant)
        return instant.astimezone(UTC)

    @staticmethod
    def _parse_text(text: str) -> datetime:
        if _TIME_TEXT_REGEX.fullmatch(text.strip()) is None:
            raise ValueError(
                f"time {text!r} must be local 'YYYY-MM-DD HH:MM' or ISO 8601 with an offset, "
                "e.g. '2025-12-17 12:00', '2025-12-17T12:00+01:00' or '2025-12-17T11:00Z'"
            )
        try:
            return datetime.fromisoformat(text.strip())
        except ValueError as error:
            raise ValueError(
                f"time {text!r} is not a valid calendar date and time (month 01-12, day of the "
                "month, hour 00-23, minute 00-59)"
            ) from error

    def _local_to_utc(self, wall_clock: datetime) -> datetime:
        earlier = wall_clock.replace(tzinfo=self._zone, fold=0)
        later = wall_clock.replace(tzinfo=self._zone, fold=1)
        if earlier.utcoffset() == later.utcoffset():
            return earlier.astimezone(UTC)
        text = wall_clock.isoformat(sep=" ", timespec="minutes")
        iso = text.replace(" ", "T")
        round_trip = earlier.astimezone(UTC).astimezone(self._zone).replace(tzinfo=None)
        if round_trip == wall_clock:
            raise ValueError(
                f"local time {text!r} is ambiguous in {self.timezone} (clocks fall back, the "
                f"hour occurs twice); give an explicit offset: '{iso}{_offset_text(earlier)}' "
                f"for the first one (summer time) or '{iso}{_offset_text(later)}' for the "
                "second one (winter time)"
            )
        raise ValueError(
            f"local time {text!r} does not exist in {self.timezone} (clocks spring forward, "
            f"the hour is skipped); write a time after the change, or the time on the clock "
            f"before the change with its offset: '{iso}{_offset_text(earlier)}'"
        )


def _offset_text(instant: datetime) -> str:
    """Format the UTC offset of an aware datetime as ``±HH:MM``."""
    text = instant.strftime("%z")
    return f"{text[:3]}:{text[3:]}"


def format_local(instant: datetime, timezone: str) -> str:
    """Format an instant for the owner: local time of ``timezone`` with UTC in brackets.

    Parameters
    ----------
    instant : datetime.datetime
        Timezone-aware instant.
    timezone : str
        IANA zone, e.g. ``"Europe/Prague"``.

    Returns
    -------
    str
        E.g. ``"2025-12-17 12:00 CET (11:00 UTC)"``; the UTC date is repeated when it differs.
    """
    local = instant.astimezone(ZoneInfo(timezone))
    utc = instant.astimezone(UTC)
    utc_text = f"{utc:%H:%M}" if utc.date() == local.date() else f"{utc:%Y-%m-%d %H:%M}"
    return f"{local:%Y-%m-%d %H:%M} {local.tzname()} ({utc_text} UTC)"


def format_local_iso(instant: datetime, timezone: str) -> str:
    """Format an instant as ready-to-paste log text: local ISO 8601 with its offset.

    Parameters
    ----------
    instant : datetime.datetime
        Timezone-aware instant.
    timezone : str
        IANA zone.

    Returns
    -------
    str
        E.g. ``"2026-04-14T01:55+02:00"``; unambiguous also in the repeated autumn hour.
    """
    local = instant.astimezone(ZoneInfo(timezone))
    return f"{local:%Y-%m-%dT%H:%M}{_offset_text(local)}"


def _timezone_of(info: ValidationInfo) -> str:
    """Return the zone named in the validation context, else :data:`DEFAULT_TIMEZONE`."""
    context = info.context
    if isinstance(context, Mapping):
        zone = context.get(TIMEZONE_CONTEXT_KEY, DEFAULT_TIMEZONE)
        if isinstance(zone, str):
            return zone
    return DEFAULT_TIMEZONE


def _to_sensor_id(value: object) -> SensorId:
    """Accept a :class:`SensorId`, any spelling :meth:`SensorId.parse` recognises or an int."""
    if isinstance(value, SensorId):
        return value
    if isinstance(value, int) and not isinstance(value, bool):
        value = str(value)
    if isinstance(value, str):
        return SensorId.parse(value)
    raise ValueError(
        f"expected a sensor name, got {type(value).__name__}; write the serial in quotes, "
        'e.g. sensor: "77799986"'
    )


AnySensorName = Annotated[
    SensorId,
    PlainValidator(_to_sensor_id),
    PlainSerializer(str, return_type=str),
    WithJsonSchema(
        {
            "type": "string",
            "minLength": 1,
            "description": (
                f"Sensor: the {SERIAL_DIGITS}-digit serial or any known spelling of its name "
                "('8615620 77799986', '77799986 (VUT)', legacy short name if unique)."
            ),
        }
    ),
]
"""A sensor named in the log; resolved to its canonical :class:`SensorId`."""

LogTime = Annotated[
    AwareDatetime,
    WithJsonSchema({"type": "string", "pattern": _JSON_TIME_PATTERN}),
]
"""A ``from`` / ``to`` value: local time or ISO 8601 with offset in the file, UTC in Python."""

LogEndTime = Annotated[
    AwareDatetime | None,
    WithJsonSchema(
        {
            "anyOf": [
                {"type": "string", "pattern": _JSON_TIME_PATTERN},
                {"const": OPEN_END},
                {"type": "null"},
            ]
        }
    ),
]
"""The ``to`` value: a time as :data:`LogTime`, or ``open`` / ``null`` for an open period."""


class OffSitePeriod(BaseModel):
    """One entry of the off-site log: a period when a sensor was not in the vineyard.

    The period is half-open: ``from <= t < to``.

    Parameters
    ----------
    sensor : SensorId
        The sensor; text in any spelling :meth:`SensorId.parse` recognises.
    from_utc : datetime.datetime
        Start (alias ``from``), inclusive. Local wall-clock time ``YYYY-MM-DD HH:MM`` of the
        zone in the validation context (key :data:`TIMEZONE_CONTEXT_KEY`, default
        Europe/Prague) or ISO 8601 with an offset or ``Z``; stored in UTC.
    to_utc : datetime.datetime or None
        End (alias ``to``), exclusive, same formats; ``open`` (or ``null``) while the sensor
        is still off site, stored as ``None``. The key is required and a blank value
        (:class:`BlankValue`) is rejected, so an open end is always written on purpose.
    reason : {"office", "service", "transport", "storage", "other"}
        Why the sensor was not in the vineyard.
    note : str or None
        Free text, optional.

    Raises
    ------
    pydantic.ValidationError
        If a time cannot be read, is ambiguous or nonexistent locally, or ``from >= to``.
    """

    model_config = ConfigDict(
        frozen=True, extra="forbid", validate_by_name=True, serialize_by_alias=True
    )

    sensor: AnySensorName = Field(description="The sensor (any known spelling of its name).")
    from_utc: LogTime = Field(
        alias="from",
        description=(
            "Start, inclusive: local time 'YYYY-MM-DD HH:MM' (Europe/Prague unless configured "
            "otherwise) or ISO 8601 with an offset or 'Z'."
        ),
    )
    to_utc: LogEndTime = Field(
        alias="to",
        description=(
            f"End, exclusive, same formats as 'from'; '{OPEN_END}' (or null) while still off site."
        ),
    )
    reason: OffSiteReason = Field(
        description="Why the sensor was not in the vineyard: office, service, transport, "
        "storage or other."
    )
    note: str | None = Field(None, min_length=1, description="Free-text note (optional).")

    @field_validator("sensor", "reason", "note", mode="before")
    @classmethod
    def _not_blank(cls, value: object, info: ValidationInfo) -> object:
        _reject_blank(value, info)
        return value

    @field_validator("from_utc", "to_utc", mode="before")
    @classmethod
    def _read_time(cls, value: object, info: ValidationInfo) -> datetime | None:
        _reject_blank(value, info)
        if value is None:
            if info.field_name == "from_utc":
                raise ValueError(BLANK_HINTS["from"])
            return None
        is_open_word = isinstance(value, str) and value.strip().lower() == OPEN_END
        if info.field_name == "to_utc" and is_open_word:
            return None
        return LocalTimeReader(_timezone_of(info)).read(value)

    @field_serializer("from_utc", "to_utc")
    def _serialize_instant(self, value: datetime | None) -> str | None:
        return None if value is None else format_utc(value)

    @model_validator(mode="after")
    def _ordered(self, info: ValidationInfo) -> Self:
        if self.to_utc is not None and not self.from_utc < self.to_utc:
            zone = _timezone_of(info)
            raise ValueError(
                f"'from' ({format_local(self.from_utc, zone)}) must be before 'to' "
                f"({format_local(self.to_utc, zone)}); swap or correct the times"
            )
        return self

    @property
    def is_open(self) -> bool:
        """``True`` while the sensor is still off site (no ``to``)."""
        return self.to_utc is None

    @property
    def detail(self) -> str:
        """``"<reason>: <note>"`` (or just the reason), the ``detail`` of the site event."""
        return self.reason if self.note is None else f"{self.reason}: {self.note}"

    def contains(self, instant: datetime | pd.Timestamp) -> bool:
        """Tell whether an instant lies in the period (``from <= t < to``).

        Parameters
        ----------
        instant : datetime.datetime or pandas.Timestamp
            Timezone-aware instant.

        Returns
        -------
        bool
            ``True`` inside the period.

        Raises
        ------
        ValueError
            If the instant is naive.
        """
        t_utc = _aware_utc(instant)
        end = self.end_ts
        return self.start_ts <= t_utc and (end is None or t_utc < end)

    def overlaps(self, start: datetime | pd.Timestamp, end: datetime | pd.Timestamp) -> bool:
        """Tell whether the period shares at least one instant with ``[start, end]``.

        Parameters
        ----------
        start, end : datetime.datetime or pandas.Timestamp
            Timezone-aware bounds, both inclusive.

        Returns
        -------
        bool
            ``True`` if some instant ``t`` with ``start <= t <= end`` lies in the period.
        """
        start_utc, end_utc = _aware_utc(start), _aware_utc(end)
        period_end = self.end_ts
        return self.start_ts <= end_utc and (period_end is None or period_end > start_utc)

    def mask(self, t_ns: npt.NDArray[np.int64]) -> npt.NDArray[np.bool_]:
        """Tell for each sample time whether it lies in the period.

        Parameters
        ----------
        t_ns : numpy.ndarray of int64
            Sample times in nanoseconds since the Unix epoch (UTC).

        Returns
        -------
        numpy.ndarray of bool
            ``True`` where ``from <= t < to``.
        """
        inside = t_ns >= self.start_ts.value
        end = self.end_ts
        if end is not None:
            inside &= t_ns < end.value
        return np.asarray(inside, dtype=np.bool_)

    @property
    def start_ts(self) -> pd.Timestamp:
        """``from`` as a UTC :class:`pandas.Timestamp` (nanoseconds)."""
        return pd.Timestamp(self.from_utc).as_unit("ns")

    @property
    def end_ts(self) -> pd.Timestamp | None:
        """``to`` as a UTC :class:`pandas.Timestamp` (nanoseconds); ``None`` while open."""
        return None if self.to_utc is None else pd.Timestamp(self.to_utc).as_unit("ns")


def _reject_blank(value: object, info: ValidationInfo) -> None:
    """Raise with a hint if a key was written without a value (or as empty text)."""
    if isinstance(value, BlankValue) or (isinstance(value, str) and not value.strip()):
        key = {"from_utc": "from", "to_utc": "to"}.get(info.field_name or "", info.field_name)
        raise ValueError(BLANK_HINTS.get(key or "", "is empty"))


def _aware_utc(instant: datetime | pd.Timestamp) -> pd.Timestamp:
    timestamp = pd.Timestamp(instant)
    if timestamp.tz is None:
        raise ValueError(f"instant must be timezone-aware, got {instant!r}")
    return timestamp.tz_convert("UTC")


class OffSiteLogFile(BaseModel):
    """The whole off-site log file: ``entries``, a list of :class:`OffSitePeriod`."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    entries: tuple[OffSitePeriod, ...] = Field(
        description="Periods when a sensor was not in the vineyard; may be empty."
    )


class OffSiteLog:
    """Validated, immutable collection of off-site periods.

    Rules: every sensor is in the registry; per sensor the periods do not overlap (touching
    is allowed: one may end exactly when the next starts); at most one period per sensor is
    open and it is the last one of that sensor.

    Parameters
    ----------
    periods : iterable of OffSitePeriod
        The periods in file order.
    registry : SensorRegistry
        The sensor registry the sensors are checked against.
    timezone : str, optional
        IANA zone in which times are shown in error messages (the log's zone).
    labels : sequence of str, optional
        How error messages name each period, e.g. ``"entry #3 (line 12)"``; default
        ``"entry #N"`` (1-based position in ``periods``).

    Raises
    ------
    OffSiteLogError
        If a rule is violated; the message names the offending entries and how to fix them.
    """

    __slots__ = ("_by_sensor", "_periods")

    def __init__(
        self,
        periods: Iterable[OffSitePeriod],
        registry: SensorRegistry,
        *,
        timezone: str = DEFAULT_TIMEZONE,
        labels: Sequence[str] | None = None,
    ) -> None:
        self._periods: tuple[OffSitePeriod, ...] = tuple(periods)
        names = list(labels) if labels is not None else []
        names += [f"entry #{index + 1}" for index in range(len(names), len(self._periods))]
        problems = [
            f"{names[index]}, 'sensor': {unknown_sensor_message(str(period.sensor), registry)}"
            for index, period in enumerate(self._periods)
            if period.sensor not in registry
        ]
        indexed: dict[SensorId, list[tuple[str, OffSitePeriod]]] = {}
        for index, period in enumerate(self._periods):
            indexed.setdefault(period.sensor, []).append((names[index], period))
        by_sensor: dict[SensorId, tuple[OffSitePeriod, ...]] = {}
        for sensor_id, entries in indexed.items():
            entries.sort(key=lambda entry: entry[1].from_utc)
            problems += _sequence_problems(entries, timezone)
            by_sensor[sensor_id] = tuple(period for _, period in entries)
        if problems:
            raise OffSiteLogError(_report(problems))
        self._by_sensor = by_sensor

    @classmethod
    def empty(cls) -> Self:
        """Return a log without periods (every sensor measures in the vineyard).

        Returns
        -------
        OffSiteLog
            The empty log.
        """
        return cls((), SensorRegistry())

    def __iter__(self) -> Iterator[OffSitePeriod]:
        return iter(self._periods)

    def __len__(self) -> int:
        return len(self._periods)

    def __repr__(self) -> str:
        return f"OffSiteLog(periods={len(self)}, sensors={len(self._by_sensor)})"

    def sensors(self) -> tuple[SensorId, ...]:
        """Return the sensors that have at least one period, sorted.

        Returns
        -------
        tuple of SensorId
            Sensor ids.
        """
        return tuple(sorted(self._by_sensor))

    def periods_for(self, sensor_id: SensorId) -> tuple[OffSitePeriod, ...]:
        """Return the periods of one sensor in time order.

        Parameters
        ----------
        sensor_id : SensorId
            The sensor.

        Returns
        -------
        tuple of OffSitePeriod
            Its periods; empty if it has none.
        """
        return self._by_sensor.get(sensor_id, ())

    def is_off_site(self, sensor_id: SensorId, instant: datetime | pd.Timestamp) -> bool:
        """Tell whether a sensor was off site at an instant.

        Parameters
        ----------
        sensor_id : SensorId
            The sensor.
        instant : datetime.datetime or pandas.Timestamp
            Timezone-aware instant.

        Returns
        -------
        bool
            ``True`` if a period of the sensor contains the instant.

        Raises
        ------
        ValueError
            If the instant is naive.
        """
        return any(period.contains(instant) for period in self.periods_for(sensor_id))

    def mask(self, series: MeasurementSeries) -> npt.NDArray[np.bool_]:
        """Tell for each row of a series whether it was recorded off site.

        Parameters
        ----------
        series : MeasurementSeries
            Measurements of one sensor.

        Returns
        -------
        numpy.ndarray of bool
            One value per row, ``True`` inside a period of ``series.sensor_id``
            (``from <= t < to``).
        """
        t_ns = series.timestamps.to_numpy(dtype="datetime64[ns]").view(np.int64)
        inside = np.zeros(len(series), dtype=np.bool_)
        for period in self.periods_for(series.sensor_id):
            inside |= period.mask(t_ns)
        return inside


def _sequence_problems(entries: Sequence[tuple[str, OffSitePeriod]], timezone: str) -> list[str]:
    """Overlaps and misplaced open periods of one sensor's entries, sorted by ``from``."""
    problems: list[str] = []
    for (label, period), (next_label, following) in pairwise(entries):
        if period.to_utc is None:
            problems.append(
                f"{label}, 'to': sensor {period.sensor} has an open period ('to: {OPEN_END}') "
                f"that is not its last one ({next_label} starts "
                f"{format_local(following.from_utc, timezone)}); write the end time into "
                f"{label} or remove the later entry"
            )
        elif period.to_utc > following.from_utc:
            problems.append(
                f"{next_label}, 'from': the period of sensor {period.sensor} starting "
                f"{format_local(following.from_utc, timezone)} overlaps {label} "
                f"({format_local(period.from_utc, timezone)} - "
                f"{format_local(period.to_utc, timezone)}); periods of one sensor must not "
                "overlap - correct the times or merge the two entries"
            )
    return problems


def unknown_sensor_message(name: str, registry: SensorRegistry) -> str:
    """Explain that a sensor is not in the registry and list the known serials.

    Parameters
    ----------
    name : str
        The sensor name as written.
    registry : SensorRegistry
        The registry.

    Returns
    -------
    str
        The message, with the fix.
    """
    known = ", ".join(str(sensor_id) for sensor_id in registry.ids()) or "none"
    return (
        f"sensor {name!r} is not in {REGISTRY_FILE_NAME} (known sensors: {known}); check the "
        "serial, or add the sensor to the registry first"
    )


def _report(problems: Iterable[str]) -> str:
    """Join problems into the text of an :class:`OffSiteLogError`."""
    return "Invalid off-site log:\n" + "\n".join(f"  {p}" for p in dict.fromkeys(problems))


class OffSiteLogSettings(BaseModel):
    """Settings of the off-site log (proposed configuration section ``offsite_log``)."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    file: Path = Field(
        Path("sensors/offsite_log.yaml"),
        description="The off-site log (path, relative to the project root).",
    )
    timezone: str = Field(
        DEFAULT_TIMEZONE,
        description=(
            "IANA zone of local times in the log (no unit); the vineyards' zone "
            "(MIGRATION_PLAN §2.8)."
        ),
    )

    @field_validator("timezone")
    @classmethod
    def _known_timezone(cls, value: str) -> str:
        LocalTimeReader(value)
        return value


class LocatedMapping(dict[Any, Any]):
    """A YAML mapping that remembers its line and the line of each key (1-based)."""

    line: int = 0
    key_lines: dict[str, int]


_YAML_MAP_TAG: Final = "tag:yaml.org,2002:map"
_YAML_NULL_TAG: Final = "tag:yaml.org,2002:null"
_YAML_NUMBER_TAGS: Final = frozenset({"tag:yaml.org,2002:int", "tag:yaml.org,2002:float"})


class StrictLogLoader(yaml.SafeLoader):
    """Safe YAML loader for the log that cannot misread a hand-edited file silently.

    * A key that appears twice in one mapping (e.g. a second ``entries:`` after uncommenting an
      example, or two ``from:`` in one entry) raises :class:`OffSiteLogError` naming the key
      and both lines; PyYAML would keep the last one without a word.
    * A key without a value (``to:``) becomes :class:`BlankValue`, not ``None``.
    * An unquoted ``sensor: 77799986`` keeps its text (no octal or float surprises).
    * Mappings are :class:`LocatedMapping` objects carrying line numbers for messages.
    """

    def construct_mapping(self, node: yaml.MappingNode, deep: bool = False) -> dict[Any, Any]:
        """Build a mapping, rejecting duplicate keys and marking blank values."""
        first_lines: dict[Any, int] = {}
        for key_node, _ in node.value:
            key = self.construct_object(key_node, deep=deep)
            line = key_node.start_mark.line + 1
            if key in first_lines:
                raise OffSiteLogError(
                    f"line {line}: the key {key!r} appears a second time (first on line "
                    f"{first_lines[key]}); keep only one - YAML would silently use the last"
                    + (
                        " (put all entries as '- sensor: ...' items under one 'entries:')"
                        if key == ENTRIES_KEY
                        else ""
                    )
                )
            first_lines[key] = line
        mapping = super().construct_mapping(node, deep=deep)
        for key_node, value_node in node.value:
            key = self.construct_object(key_node, deep=deep)
            if isinstance(value_node, yaml.ScalarNode) and value_node.style is None:
                if value_node.tag == _YAML_NULL_TAG and value_node.value == "":
                    mapping[key] = BlankValue()
                elif key == "sensor" and value_node.tag in _YAML_NUMBER_TAGS:
                    mapping[key] = value_node.value
        return mapping

    def construct_located_mapping(self, node: yaml.MappingNode) -> Iterator[LocatedMapping]:
        """Constructor of YAML mappings: a :class:`LocatedMapping` with line numbers."""
        data = LocatedMapping()
        data.line = node.start_mark.line + 1
        data.key_lines = {
            str(key_node.value): key_node.start_mark.line + 1 for key_node, _ in node.value
        }
        yield data
        data.update(self.construct_mapping(node))

    yaml_constructors = {  # noqa: RUF012 - the per-class constructor registry of PyYAML
        **yaml.SafeLoader.yaml_constructors,
        _YAML_MAP_TAG: construct_located_mapping,
    }


class OffSiteLogStore:
    """Read the off-site log file ``sensors/offsite_log.yaml``."""

    def load(
        self, path: Path, registry: SensorRegistry, timezone: str = DEFAULT_TIMEZONE
    ) -> OffSiteLog:
        """Read and validate the log file.

        Parameters
        ----------
        path : pathlib.Path
            The YAML file.
        registry : SensorRegistry
            Sensor registry; resolves every spelling of a sensor name (including a unique
            legacy short name) and rejects unknown sensors.
        timezone : str, optional
            IANA zone of local times in the file.

        Returns
        -------
        OffSiteLog
            The validated log.

        Raises
        ------
        OffSiteLogError
            If the file cannot be read or is invalid; the message names every offending entry
            (``entry #N``, 1-based, with its line) and field, and says how to fix it.
        """
        try:
            text = path.read_text(encoding=FILE_ENCODING)
        except OSError as error:
            raise OffSiteLogError(f"Cannot read off-site log {path}: {error}") from error
        try:
            log = self.loads(text, registry, timezone)
        except OffSiteLogError as error:
            raise OffSiteLogError(f"{path}: {error}") from error
        logger.info("Loaded %d off-site period(s) from %s", len(log), path)
        return log

    def loads(
        self, text: str, registry: SensorRegistry, timezone: str = DEFAULT_TIMEZONE
    ) -> OffSiteLog:
        """Validate the text of a log file (see :meth:`load`).

        Parameters
        ----------
        text : str
            YAML text.
        registry : SensorRegistry
            Sensor registry.
        timezone : str, optional
            IANA zone of local times.

        Returns
        -------
        OffSiteLog
            The validated log.

        Raises
        ------
        OffSiteLogError
            If the text is invalid.
        """
        try:
            LocalTimeReader(timezone)
        except ValueError as error:
            raise OffSiteLogError(str(error)) from error
        entries = _entries(_parse_yaml(text))
        labels = [_label(index, entry) for index, entry in enumerate(entries)]
        problems: list[str] = []
        periods: list[OffSitePeriod] = []
        for index, entry in enumerate(entries):
            reader = _EntryReader(index, labels[index], registry, timezone)
            period = reader.read(entry)
            problems += reader.problems
            if period is not None:
                periods.append(period)
        if problems:
            raise OffSiteLogError(_report(problems))
        return OffSiteLog(periods, registry, timezone=timezone, labels=labels)


def _parse_yaml(text: str) -> Any:
    try:
        return yaml.load(text, Loader=StrictLogLoader)
    except yaml.YAMLError as error:
        raise OffSiteLogError(
            f"not valid YAML (indent with spaces, not tabs; put times and notes in quotes): {error}"
        ) from error


def _entries(raw: Any) -> list[Any]:
    """Return the list under ``entries`` or raise with a hint about the file structure."""
    hint = (
        f"the file must contain one key '{ENTRIES_KEY}:' with a list of entries "
        f"('- sensor: ...'); write '{ENTRIES_KEY}: []' when there are no periods"
    )
    if isinstance(raw, dict):
        unknown = sorted(str(key) for key in raw if key != ENTRIES_KEY)
        if unknown:
            lines = raw.key_lines if isinstance(raw, LocatedMapping) else {}
            where = ", ".join(f"{key!r} (line {lines.get(key, '?')})" for key in unknown)
            raise OffSiteLogError(f"unknown top-level key(s) {where}; {hint}")
    if not isinstance(raw, dict) or not isinstance(raw.get(ENTRIES_KEY), list):
        raise OffSiteLogError(hint)
    entries: list[Any] = raw[ENTRIES_KEY]
    return entries


def _label(index: int, entry: object) -> str:
    """``entry #N (line L)``: how messages name an entry (1-based, as a person counts)."""
    if isinstance(entry, LocatedMapping):
        return f"entry #{index + 1} (line {entry.line})"
    return f"entry #{index + 1}"


_FIX_HINTS: Final[Mapping[str, str]] = {
    "literal_error": " (lower case, exactly one of these)",
    "string_type": " - put the text in quotes",
}
"""Fix appended to pydantic messages by error type."""


class _EntryReader:
    """Validate one raw entry into an :class:`OffSitePeriod` and collect readable problems."""

    def __init__(self, index: int, label: str, registry: SensorRegistry, timezone: str) -> None:
        self._number = f"entry #{index + 1}"
        self._label = label
        self._registry = registry
        self._timezone = timezone
        self.problems: list[str] = []

    def read(self, entry: object) -> OffSitePeriod | None:
        if not isinstance(entry, dict):
            self.problems.append(
                f"{self._label}: must be a list item of keys, starting with "
                f"'- {EXAMPLE_LINES['sensor']}' followed by indented from/to/reason lines"
            )
            return None
        lines = entry.key_lines if isinstance(entry, LocatedMapping) else {}
        values = dict(entry)
        sensor_failed = self._resolve_sensor(values, lines)
        try:
            return OffSitePeriod.model_validate(
                values, context={TIMEZONE_CONTEXT_KEY: self._timezone}
            )
        except ValidationError as error:
            for issue in error.errors():
                field = str(issue["loc"][0]) if issue["loc"] else ""
                if not (sensor_failed and field == "sensor"):
                    self.problems.append(self._describe(issue, field, lines))
            return None

    def _resolve_sensor(self, values: dict[Any, Any], lines: Mapping[str, int]) -> bool:
        """Replace the sensor name by its canonical serial; ``True`` if that failed."""
        name = values.get("sensor")
        if not isinstance(name, str) or not name.strip():
            return False
        try:
            values["sensor"] = str(self._registry.get(name).id)
        except SensorLookupError as error:
            message = str(error)
            if not isinstance(error, AmbiguousSensorNameError):
                message = unknown_sensor_message(name, self._registry)
            self.problems.append(f"{self._where('sensor', lines)}: {message}")
            return True
        return False

    def _where(self, field: str, lines: Mapping[str, int]) -> str:
        line = lines.get(field)
        if line is None:
            return f"{self._label}, '{field}'"
        return f"{self._number}, '{field}' (line {line})"

    def _describe(self, issue: Mapping[str, Any], field: str, lines: Mapping[str, int]) -> str:
        kind = issue["type"]
        if kind == "missing":
            return (
                f"{self._label}: the key '{field}' is missing - add a line like "
                f"{EXAMPLE_LINES.get(field, field + ': ...')}"
            )
        if kind == "extra_forbidden":
            return (
                f"{self._where(field, lines)}: unknown key '{field}' - allowed keys are "
                f"{', '.join(ENTRY_KEYS)} (check the spelling)"
            )
        message = str(issue["msg"]).removeprefix("Value error, ")
        message += _FIX_HINTS.get(kind, "")
        if not field:
            return f"{self._label}: {message}"
        return f"{self._where(field, lines)}: {message}"


SCHEMA_TITLE: Final = "SIVIN off-site log"
"""Title of the generated schema."""

SCHEMA_DESCRIPTION: Final = (
    "sensors/offsite_log.yaml: periods when a sensor was NOT measuring in the vineyard "
    "(MIGRATION_PLAN §2.8). Generated from sivin.registry.offsite; do not edit by hand."
)
"""Description of the generated schema."""

JSON_SCHEMA_DIALECT: Final = "https://json-schema.org/draft/2020-12/schema"
"""JSON Schema dialect emitted by pydantic v2."""


def build_json_schema() -> dict[str, Any]:
    """Build the JSON Schema of the off-site log file.

    The schema checks the structure of every entry. Rules that relate entries (known sensor,
    no overlaps, open period last) and the daylight-saving checks of local times are applied
    by :class:`OffSiteLogStore` and documented in ``docs/sensors.md``.

    Returns
    -------
    dict
        JSON Schema (draft 2020-12) with the file's keys (``from``, ``to``).
    """
    generated = OffSiteLogFile.model_json_schema(by_alias=True, mode="validation")
    for definition in generated.get("$defs", {}).values():
        definition["description"] = definition.get("description", "").split("\n\n", 1)[0]
        definition["description"] = definition["description"].replace("\n", " ")
    generated["title"] = SCHEMA_TITLE
    generated["description"] = SCHEMA_DESCRIPTION
    return {"$schema": JSON_SCHEMA_DIALECT, **generated}


def render_json_schema() -> str:
    """Render :func:`build_json_schema` as the canonical text of ``offsite_log.schema.json``.

    Returns
    -------
    str
        JSON text with 2-space indentation and a trailing newline.
    """
    return render_json(build_json_schema())
