"""The off-site log: periods when a sensor was NOT measuring in the vineyard (MIGRATION_PLAN §2.8).

By default every sensor is assumed to measure in the vineyard. The owner keeps a hand-written
file, ``sensors/offsite_log.yaml``, with the periods when a sensor was elsewhere (office,
service, transport, storage). Quality control marks the samples of these periods
``PRE_DEPLOYMENT`` (:class:`~sivin.quality.checks.offsite.OffSiteCheck`) and the web portal draws
them as a grey band.

* :class:`OffSitePeriod` is one entry of the file: sensor, ``from``, ``to`` (``null`` while the
  sensor is still off site), reason and note. Times are local wall-clock time
  (``YYYY-MM-DD HH:MM``, Europe/Prague by default) or ISO 8601 with an explicit offset or ``Z``;
  they are stored in UTC. A local time that is ambiguous or does not exist because of a
  daylight-saving change is rejected with a request for an explicit offset.
* :class:`OffSiteLog` is the validated, immutable collection: known sensors only, no overlaps
  per sensor, at most one open period per sensor and it must be the last.
* :class:`OffSiteLogStore` reads the YAML file; every error names the entry index and field.

The JSON Schema ``sensors/offsite_log.schema.json`` is generated by :func:`render_json_schema`.
"""

from __future__ import annotations

import logging
import re
from collections.abc import Iterable, Iterator, Mapping, Sequence
from datetime import UTC, date, datetime
from itertools import pairwise
from pathlib import Path
from typing import Annotated, Any, Final, Literal, Self
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

import numpy as np
import numpy.typing as npt
import pandas as pd
import yaml
from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    PlainSerializer,
    PlainValidator,
    ValidationError,
    ValidationInfo,
    WithJsonSchema,
    field_serializer,
    field_validator,
    model_validator,
)

from sivin.core.defaults import DEFAULT_TIMEZONE
from sivin.core.ids import SERIAL_DIGITS, SensorId
from sivin.core.schema import MeasurementSeries
from sivin.registry.errors import SensorLookupError
from sivin.registry.geojson import FILE_ENCODING, render_json
from sivin.registry.model import format_utc
from sivin.registry.registry import SensorRegistry

logger = logging.getLogger(__name__)

OffSiteReason = Literal["office", "service", "transport", "storage", "other"]
"""Why a sensor was not in the vineyard (the ``reason`` of an entry)."""

TIMEZONE_CONTEXT_KEY: Final = "timezone"
"""Key of the pydantic validation context that names the IANA zone of local times."""

TIME_TEXT_PATTERN: Final = (
    r"^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]{1,6})?)?"
    r"(?P<offset>Z|[+-][0-9]{2}:[0-9]{2})?$"
)
"""Accepted text of ``from`` / ``to``: local ``YYYY-MM-DD HH:MM[:SS]`` or the same with an offset.

Without ``offset`` the time is local wall-clock time of the log's zone; with ``Z`` or
``±HH:MM`` it is an absolute instant.
"""

_TIME_TEXT_REGEX: Final = re.compile(TIME_TEXT_PATTERN)

_JSON_TIME_PATTERN: Final = TIME_TEXT_PATTERN.replace("?P<offset>", "")
""":data:`TIME_TEXT_PATTERN` without the Python-only named group (for the JSON Schema)."""

ENTRIES_KEY: Final = "entries"
"""Top-level key of the log file: the list of entries."""


class OffSiteLogError(ValueError):
    """Raised when the off-site log cannot be read or violates a rule; names entry and field."""


class LocalTimeReader:
    """Read the time values of the log as UTC instants.

    Parameters
    ----------
    timezone : str
        IANA zone of local wall-clock times, e.g. ``"Europe/Prague"``.

    Raises
    ------
    ValueError
        If the zone is unknown.
    """

    __slots__ = ("_zone",)

    def __init__(self, timezone: str) -> None:
        try:
            self._zone = ZoneInfo(timezone)
        except (ZoneInfoNotFoundError, ValueError) as error:
            raise ValueError(f"unknown IANA time zone {timezone!r}") from error

    @property
    def timezone(self) -> str:
        """The IANA zone name."""
        return self._zone.key

    def read(self, value: object) -> datetime:
        """Convert one ``from`` / ``to`` value to an aware UTC datetime.

        Parameters
        ----------
        value : str or datetime.datetime
            Text matching :data:`TIME_TEXT_PATTERN`, or a datetime as produced by the YAML
            parser for an unquoted ``2025-12-17 12:00:00`` (naive = local wall-clock time).

        Returns
        -------
        datetime.datetime
            The instant in UTC.

        Raises
        ------
        ValueError
            If the value is not a time, has no time of day, or is a local time that is
            ambiguous or does not exist in the zone (daylight-saving change).
        """
        if isinstance(value, datetime):
            instant = value
        elif isinstance(value, date):
            raise ValueError(
                f"{value.isoformat()!r} has no time of day; write 'YYYY-MM-DD HH:MM', "
                f"e.g. '{value.isoformat()} 12:00'"
            )
        elif isinstance(value, str):
            instant = self._parse_text(value)
        else:
            raise ValueError(f"expected a time as text, got {type(value).__name__}")
        if instant.tzinfo is None:
            return self._local_to_utc(instant)
        return instant.astimezone(UTC)

    @staticmethod
    def _parse_text(text: str) -> datetime:
        if _TIME_TEXT_REGEX.fullmatch(text.strip()) is None:
            raise ValueError(
                f"time {text!r} must be local 'YYYY-MM-DD HH:MM' or ISO 8601 with an offset, "
                "e.g. '2025-12-17 12:00', '2025-12-17T12:00+01:00' or '2025-12-17T11:00Z'"
            )
        try:
            return datetime.fromisoformat(text.strip())
        except ValueError as error:
            raise ValueError(f"time {text!r} is not a valid calendar date and time") from error

    def _local_to_utc(self, wall_clock: datetime) -> datetime:
        earlier = wall_clock.replace(tzinfo=self._zone, fold=0)
        later = wall_clock.replace(tzinfo=self._zone, fold=1)
        if earlier.utcoffset() == later.utcoffset():
            return earlier.astimezone(UTC)
        text = wall_clock.isoformat(sep=" ", timespec="minutes")
        offsets = sorted({_offset_text(earlier), _offset_text(later)}, reverse=True)
        round_trip = earlier.astimezone(UTC).astimezone(self._zone).replace(tzinfo=None)
        if round_trip == wall_clock:
            problem = "is ambiguous (clocks fall back, the hour occurs twice)"
        else:
            problem = "does not exist (clocks spring forward, the hour is skipped)"
        examples = " or ".join(f"'{text.replace(' ', 'T')}{offset}'" for offset in offsets)
        raise ValueError(
            f"local time {text!r} {problem} in {self.timezone}; give an explicit offset, "
            f"e.g. {examples}"
        )


def _offset_text(instant: datetime) -> str:
    """Format the UTC offset of an aware datetime as ``±HH:MM``."""
    text = instant.strftime("%z")
    return f"{text[:3]}:{text[3:]}"


def _timezone_of(info: ValidationInfo) -> str:
    """Return the zone named in the validation context, else :data:`DEFAULT_TIMEZONE`."""
    context = info.context
    if isinstance(context, Mapping):
        zone = context.get(TIMEZONE_CONTEXT_KEY, DEFAULT_TIMEZONE)
        if isinstance(zone, str):
            return zone
    return DEFAULT_TIMEZONE


def _to_sensor_id(value: object) -> SensorId:
    """Accept a :class:`SensorId` or any spelling :meth:`SensorId.parse` recognises."""
    if isinstance(value, SensorId):
        return value
    if isinstance(value, str):
        return SensorId.parse(value)
    raise ValueError(f"expected a sensor name as text, got {type(value).__name__}")


AnySensorName = Annotated[
    SensorId,
    PlainValidator(_to_sensor_id),
    PlainSerializer(str, return_type=str),
    WithJsonSchema(
        {
            "type": "string",
            "minLength": 1,
            "description": (
                f"Sensor: the {SERIAL_DIGITS}-digit serial or any known spelling of its name "
                "('8615620 77799986', '77799986 (VUT)', legacy short name if unique)."
            ),
        }
    ),
]
"""A sensor named in the log; resolved to its canonical :class:`SensorId`."""

LogTime = Annotated[
    AwareDatetime,
    WithJsonSchema({"type": "string", "pattern": _JSON_TIME_PATTERN}),
]
"""A ``from`` / ``to`` value: local time or ISO 8601 with offset in the file, UTC in Python."""


class OffSitePeriod(BaseModel):
    """One entry of the off-site log: a period when a sensor was not in the vineyard.

    The period is half-open: ``from <= t < to``.

    Parameters
    ----------
    sensor : SensorId
        The sensor; text in any spelling :meth:`SensorId.parse` recognises.
    from_utc : datetime.datetime
        Start (alias ``from``), inclusive. Local wall-clock time ``YYYY-MM-DD HH:MM`` of the
        zone in the validation context (key :data:`TIMEZONE_CONTEXT_KEY`, default
        Europe/Prague) or ISO 8601 with an offset or ``Z``; stored in UTC.
    to_utc : datetime.datetime or None
        End (alias ``to``), exclusive, same formats; ``None`` while the sensor is still off
        site. The key is required, so an open end is always written on purpose.
    reason : {"office", "service", "transport", "storage", "other"}
        Why the sensor was not in the vineyard.
    note : str or None
        Free text, optional.

    Raises
    ------
    pydantic.ValidationError
        If a time cannot be read, is ambiguous or nonexistent locally, or ``from >= to``.
    """

    model_config = ConfigDict(
        frozen=True, extra="forbid", validate_by_name=True, serialize_by_alias=True
    )

    sensor: AnySensorName = Field(description="The sensor (any known spelling of its name).")
    from_utc: LogTime = Field(
        alias="from",
        description=(
            "Start, inclusive: local time 'YYYY-MM-DD HH:MM' (Europe/Prague unless configured "
            "otherwise) or ISO 8601 with an offset or 'Z'."
        ),
    )
    to_utc: LogTime | None = Field(
        alias="to",
        description="End, exclusive, same formats as 'from'; null while still off site.",
    )
    reason: OffSiteReason = Field(
        description="Why the sensor was not in the vineyard: office, service, transport, "
        "storage or other."
    )
    note: str | None = Field(None, min_length=1, description="Free-text note (optional).")

    @field_validator("from_utc", "to_utc", mode="before")
    @classmethod
    def _read_time(cls, value: object, info: ValidationInfo) -> datetime | None:
        if value is None:
            return None
        return LocalTimeReader(_timezone_of(info)).read(value)

    @field_serializer("from_utc", "to_utc")
    def _serialize_instant(self, value: datetime | None) -> str | None:
        return None if value is None else format_utc(value)

    @model_validator(mode="after")
    def _ordered(self) -> Self:
        if self.to_utc is not None and not self.from_utc < self.to_utc:
            raise ValueError(
                f"'from' ({format_utc(self.from_utc)}) must be before 'to' "
                f"({format_utc(self.to_utc)}), both in UTC"
            )
        return self

    @property
    def is_open(self) -> bool:
        """``True`` while the sensor is still off site (no ``to``)."""
        return self.to_utc is None

    @property
    def detail(self) -> str:
        """``"<reason>: <note>"`` (or just the reason), the ``detail`` of the site event."""
        return self.reason if self.note is None else f"{self.reason}: {self.note}"

    def contains(self, instant: datetime | pd.Timestamp) -> bool:
        """Tell whether an instant lies in the period (``from <= t < to``).

        Parameters
        ----------
        instant : datetime.datetime or pandas.Timestamp
            Timezone-aware instant.

        Returns
        -------
        bool
            ``True`` inside the period.

        Raises
        ------
        ValueError
            If the instant is naive.
        """
        t_utc = _aware_utc(instant)
        end = self.end_ts
        return self.start_ts <= t_utc and (end is None or t_utc < end)

    def overlaps(self, start: datetime | pd.Timestamp, end: datetime | pd.Timestamp) -> bool:
        """Tell whether the period shares at least one instant with ``[start, end]``.

        Parameters
        ----------
        start, end : datetime.datetime or pandas.Timestamp
            Timezone-aware bounds, both inclusive.

        Returns
        -------
        bool
            ``True`` if some instant ``t`` with ``start <= t <= end`` lies in the period.
        """
        start_utc, end_utc = _aware_utc(start), _aware_utc(end)
        period_end = self.end_ts
        return self.start_ts <= end_utc and (period_end is None or period_end > start_utc)

    def mask(self, t_ns: npt.NDArray[np.int64]) -> npt.NDArray[np.bool_]:
        """Tell for each sample time whether it lies in the period.

        Parameters
        ----------
        t_ns : numpy.ndarray of int64
            Sample times in nanoseconds since the Unix epoch (UTC).

        Returns
        -------
        numpy.ndarray of bool
            ``True`` where ``from <= t < to``.
        """
        inside = t_ns >= self.start_ts.value
        end = self.end_ts
        if end is not None:
            inside &= t_ns < end.value
        return np.asarray(inside, dtype=np.bool_)

    @property
    def start_ts(self) -> pd.Timestamp:
        """``from`` as a UTC :class:`pandas.Timestamp` (nanoseconds)."""
        return pd.Timestamp(self.from_utc).as_unit("ns")

    @property
    def end_ts(self) -> pd.Timestamp | None:
        """``to`` as a UTC :class:`pandas.Timestamp` (nanoseconds); ``None`` while open."""
        return None if self.to_utc is None else pd.Timestamp(self.to_utc).as_unit("ns")


def _aware_utc(instant: datetime | pd.Timestamp) -> pd.Timestamp:
    timestamp = pd.Timestamp(instant)
    if timestamp.tz is None:
        raise ValueError(f"instant must be timezone-aware, got {instant!r}")
    return timestamp.tz_convert("UTC")


class OffSiteLogFile(BaseModel):
    """The whole off-site log file: ``entries``, a list of :class:`OffSitePeriod`."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    entries: tuple[OffSitePeriod, ...] = Field(
        description="Periods when a sensor was not in the vineyard; may be empty."
    )


class OffSiteLog:
    """Validated, immutable collection of off-site periods.

    Rules: every sensor is in the registry; per sensor the periods do not overlap (touching
    is allowed: one may end exactly when the next starts); at most one period per sensor is
    open and it is the last one of that sensor.

    Parameters
    ----------
    periods : iterable of OffSitePeriod
        The periods in file order; error messages refer to their position as ``entries[i]``.
    registry : SensorRegistry
        The sensor registry the sensors are checked against.

    Raises
    ------
    OffSiteLogError
        If a rule is violated; the message names the offending entries.
    """

    __slots__ = ("_by_sensor", "_periods")

    def __init__(self, periods: Iterable[OffSitePeriod], registry: SensorRegistry) -> None:
        self._periods: tuple[OffSitePeriod, ...] = tuple(periods)
        problems = [
            f"entries[{index}].sensor: sensor {period.sensor} is not in the sensor registry"
            for index, period in enumerate(self._periods)
            if period.sensor not in registry
        ]
        indexed: dict[SensorId, list[tuple[int, OffSitePeriod]]] = {}
        for index, period in enumerate(self._periods):
            indexed.setdefault(period.sensor, []).append((index, period))
        by_sensor: dict[SensorId, tuple[OffSitePeriod, ...]] = {}
        for sensor_id, entries in indexed.items():
            entries.sort(key=lambda entry: entry[1].from_utc)
            problems += _sequence_problems(entries)
            by_sensor[sensor_id] = tuple(period for _, period in entries)
        if problems:
            raise OffSiteLogError("Invalid off-site log:\n" + "\n".join(f"  {p}" for p in problems))
        self._by_sensor = by_sensor

    @classmethod
    def empty(cls) -> Self:
        """Return a log without periods (every sensor measures in the vineyard).

        Returns
        -------
        OffSiteLog
            The empty log.
        """
        return cls((), SensorRegistry())

    def __iter__(self) -> Iterator[OffSitePeriod]:
        return iter(self._periods)

    def __len__(self) -> int:
        return len(self._periods)

    def __repr__(self) -> str:
        return f"OffSiteLog(periods={len(self)}, sensors={len(self._by_sensor)})"

    def sensors(self) -> tuple[SensorId, ...]:
        """Return the sensors that have at least one period, sorted.

        Returns
        -------
        tuple of SensorId
            Sensor ids.
        """
        return tuple(sorted(self._by_sensor))

    def periods_for(self, sensor_id: SensorId) -> tuple[OffSitePeriod, ...]:
        """Return the periods of one sensor in time order.

        Parameters
        ----------
        sensor_id : SensorId
            The sensor.

        Returns
        -------
        tuple of OffSitePeriod
            Its periods; empty if it has none.
        """
        return self._by_sensor.get(sensor_id, ())

    def is_off_site(self, sensor_id: SensorId, instant: datetime | pd.Timestamp) -> bool:
        """Tell whether a sensor was off site at an instant.

        Parameters
        ----------
        sensor_id : SensorId
            The sensor.
        instant : datetime.datetime or pandas.Timestamp
            Timezone-aware instant.

        Returns
        -------
        bool
            ``True`` if a period of the sensor contains the instant.

        Raises
        ------
        ValueError
            If the instant is naive.
        """
        return any(period.contains(instant) for period in self.periods_for(sensor_id))

    def mask(self, series: MeasurementSeries) -> npt.NDArray[np.bool_]:
        """Tell for each row of a series whether it was recorded off site.

        Parameters
        ----------
        series : MeasurementSeries
            Measurements of one sensor.

        Returns
        -------
        numpy.ndarray of bool
            One value per row, ``True`` inside a period of ``series.sensor_id``
            (``from <= t < to``).
        """
        t_ns = series.timestamps.to_numpy(dtype="datetime64[ns]").view(np.int64)
        inside = np.zeros(len(series), dtype=np.bool_)
        for period in self.periods_for(series.sensor_id):
            inside |= period.mask(t_ns)
        return inside


def _sequence_problems(entries: Sequence[tuple[int, OffSitePeriod]]) -> list[str]:
    """Overlaps and misplaced open periods of one sensor's entries, sorted by ``from``."""
    problems: list[str] = []
    for (index, period), (next_index, following) in pairwise(entries):
        if period.to_utc is None:
            problems.append(
                f"entries[{index}].to: sensor {period.sensor} has an open period (to: null) "
                f"that is not its last one (entries[{next_index}] starts "
                f"{format_utc(following.from_utc)}); close it or remove the later entry"
            )
        elif period.to_utc > following.from_utc:
            problems.append(
                f"entries[{next_index}].from: period of sensor {period.sensor} starting "
                f"{format_utc(following.from_utc)} overlaps entries[{index}] "
                f"({format_utc(period.from_utc)} - {format_utc(period.to_utc)}, UTC)"
            )
    return problems


class OffSiteLogSettings(BaseModel):
    """Settings of the off-site log (proposed configuration section ``offsite_log``)."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    file: Path = Field(
        Path("sensors/offsite_log.yaml"),
        description="The off-site log (path, relative to the project root).",
    )
    timezone: str = Field(
        DEFAULT_TIMEZONE,
        description=(
            "IANA zone of local times in the log (no unit); the vineyards' zone "
            "(MIGRATION_PLAN §2.8)."
        ),
    )

    @field_validator("timezone")
    @classmethod
    def _known_timezone(cls, value: str) -> str:
        LocalTimeReader(value)
        return value


class OffSiteLogStore:
    """Read the off-site log file ``sensors/offsite_log.yaml``."""

    def load(
        self, path: Path, registry: SensorRegistry, timezone: str = DEFAULT_TIMEZONE
    ) -> OffSiteLog:
        """Read and validate the log file.

        Parameters
        ----------
        path : pathlib.Path
            The YAML file.
        registry : SensorRegistry
            Sensor registry; resolves every spelling of a sensor name (including a unique
            legacy short name) and rejects unknown sensors.
        timezone : str, optional
            IANA zone of local times in the file.

        Returns
        -------
        OffSiteLog
            The validated log.

        Raises
        ------
        OffSiteLogError
            If the file cannot be read or is invalid; the message names every offending entry
            and field, e.g. ``entries.2.from``.
        """
        try:
            text = path.read_text(encoding=FILE_ENCODING)
        except OSError as error:
            raise OffSiteLogError(f"Cannot read off-site log {path}: {error}") from error
        try:
            log = self.loads(text, registry, timezone)
        except OffSiteLogError as error:
            raise OffSiteLogError(f"{path}: {error}") from error
        logger.info("Loaded %d off-site period(s) from %s", len(log), path)
        return log

    def loads(
        self, text: str, registry: SensorRegistry, timezone: str = DEFAULT_TIMEZONE
    ) -> OffSiteLog:
        """Validate the text of a log file (see :meth:`load`).

        Parameters
        ----------
        text : str
            YAML text.
        registry : SensorRegistry
            Sensor registry.
        timezone : str, optional
            IANA zone of local times.

        Returns
        -------
        OffSiteLog
            The validated log.

        Raises
        ------
        OffSiteLogError
            If the text is invalid.
        """
        try:
            LocalTimeReader(timezone)
            raw: Any = yaml.safe_load(text)
        except ValueError as error:
            raise OffSiteLogError(str(error)) from error
        except yaml.YAMLError as error:
            raise OffSiteLogError(f"not valid YAML: {error}") from error
        if not isinstance(raw, dict) or not isinstance(raw.get(ENTRIES_KEY), list):
            raise OffSiteLogError(
                f"the file must be a mapping with a list '{ENTRIES_KEY}' (use '{ENTRIES_KEY}: []' "
                "for no periods)"
            )
        unresolved, resolved = _resolve_sensors(raw[ENTRIES_KEY], registry)
        problems = list(unresolved.values())
        try:
            parsed = OffSiteLogFile.model_validate(
                {**raw, ENTRIES_KEY: resolved}, context={TIMEZONE_CONTEXT_KEY: timezone}
            )
        except ValidationError as error:
            problems += [
                _describe(issue)
                for issue in error.errors()
                if tuple(issue["loc"]) not in {(ENTRIES_KEY, i, "sensor") for i in unresolved}
            ]
            parsed = None
        if problems or parsed is None:
            raise OffSiteLogError(
                "Invalid off-site log:\n" + "\n".join(f"  {p}" for p in dict.fromkeys(problems))
            )
        return OffSiteLog(parsed.entries, registry)


def _resolve_sensors(
    entries: list[Any], registry: SensorRegistry
) -> tuple[dict[int, str], list[Any]]:
    """Replace every sensor name by its canonical serial; report the names that fail by index."""
    problems: dict[int, str] = {}
    resolved: list[Any] = []
    for index, entry in enumerate(entries):
        name = entry.get("sensor") if isinstance(entry, dict) else None
        if not isinstance(name, str):
            resolved.append(entry)
            continue
        try:
            canonical = str(registry.get(name).id)
        except SensorLookupError as error:
            problems[index] = f"{ENTRIES_KEY}.{index}.sensor: {error}"
            canonical = name
        resolved.append({**entry, "sensor": canonical})
    return problems, resolved


def _describe(issue: Mapping[str, Any]) -> str:
    """Format one pydantic error as ``entries.<i>.<field>: <message>`` with file keys."""
    location = ".".join(str(part) for part in issue["loc"]) or "<root>"
    return f"{location}: {issue['msg']}"


SCHEMA_TITLE: Final = "SIVIN off-site log"
"""Title of the generated schema."""

SCHEMA_DESCRIPTION: Final = (
    "sensors/offsite_log.yaml: periods when a sensor was NOT measuring in the vineyard "
    "(MIGRATION_PLAN §2.8). Generated from sivin.registry.offsite; do not edit by hand."
)
"""Description of the generated schema."""

JSON_SCHEMA_DIALECT: Final = "https://json-schema.org/draft/2020-12/schema"
"""JSON Schema dialect emitted by pydantic v2."""


def build_json_schema() -> dict[str, Any]:
    """Build the JSON Schema of the off-site log file.

    The schema checks the structure of every entry. Rules that relate entries (known sensor,
    no overlaps, open period last) and the daylight-saving checks of local times are applied
    by :class:`OffSiteLogStore` and documented in ``docs/sensors.md``.

    Returns
    -------
    dict
        JSON Schema (draft 2020-12) with the file's keys (``from``, ``to``).
    """
    generated = OffSiteLogFile.model_json_schema(by_alias=True, mode="validation")
    for definition in generated.get("$defs", {}).values():
        definition["description"] = definition.get("description", "").split("\n\n", 1)[0]
        definition["description"] = definition["description"].replace("\n", " ")
    generated["title"] = SCHEMA_TITLE
    generated["description"] = SCHEMA_DESCRIPTION
    return {"$schema": JSON_SCHEMA_DIALECT, **generated}


def render_json_schema() -> str:
    """Render :func:`build_json_schema` as the canonical text of ``offsite_log.schema.json``.

    Returns
    -------
    str
        JSON text with 2-space indentation and a trailing newline.
    """
    return render_json(build_json_schema())
