"""The off-site log: periods when a sensor was NOT measuring in the vineyard (MIGRATION_PLAN §2.8).

By default every sensor is assumed to measure in the vineyard. The owner keeps a hand-written
file, ``sensors/offsite_log.yaml``, with the periods when a sensor was elsewhere (office,
service, transport, storage). Quality control marks the samples of these periods
``PRE_DEPLOYMENT`` (:class:`~sivin.quality.checks.offsite.OffSiteCheck`) and the web portal draws
them as a grey band.

* :class:`OffSitePeriod` is one entry of the file: sensor, ``from``, ``to`` (``open`` or
  ``null`` while the sensor is still off site; a blank ``to:`` is an error), reason and note.
  Times are local wall-clock time (``YYYY-MM-DD HH:MM``, Europe/Prague by default) or ISO 8601
  with an explicit offset or ``Z``; they are stored in UTC. A local time that is ambiguous or
  does not exist because of a daylight-saving change is rejected with a request for an
  explicit offset.
* :class:`OffSiteLog` is the validated, immutable collection: known sensors only, no overlaps
  per sensor, at most one open period per sensor and it must be the last.
* :class:`OffSiteLogStore` reads the YAML file strictly (a duplicate key is an error, not "last
  one wins"); every error names the entry as ``entry #N`` (1-based) with its line and field, and
  says how to fix it. Times in messages are local time of the log's zone with UTC in brackets.

The JSON Schema ``sensors/offsite_log.schema.json`` is generated by :func:`render_json_schema`.

Modules: :mod:`.model` (period and log), :mod:`.local_time` (local times), :mod:`.strict_yaml`
(the strict loader), :mod:`.store` (reading the file and error texts), :mod:`.messages`
(error type and hints), :mod:`.settings`, :mod:`.schema`. The public API is re-exported here.
"""

from sivin.registry.offsite.local_time import (
    TIME_TEXT_PATTERN,
    TIMEZONE_CONTEXT_KEY,
    LocalTimeReader,
    format_local,
    format_local_iso,
)
from sivin.registry.offsite.messages import (
    BLANK_HINTS,
    ENTRIES_KEY,
    ENTRY_KEYS,
    EXAMPLE_LINES,
    OPEN_END,
    REGISTRY_FILE_NAME,
    OffSiteLogError,
    unknown_sensor_message,
)
from sivin.registry.offsite.model import (
    AnySensorName,
    LogEndTime,
    LogTime,
    OffSiteLog,
    OffSiteLogFile,
    OffSitePeriod,
    OffSiteReason,
    public_reason,
)
from sivin.registry.offsite.schema import (
    JSON_SCHEMA_DIALECT,
    SCHEMA_DESCRIPTION,
    SCHEMA_TITLE,
    build_json_schema,
    render_json_schema,
)
from sivin.registry.offsite.settings import OffSiteLogSettings
from sivin.registry.offsite.store import OffSiteLogStore
from sivin.registry.offsite.strict_yaml import BlankValue, LocatedMapping, StrictLogLoader

__all__ = [
    "BLANK_HINTS",
    "ENTRIES_KEY",
    "ENTRY_KEYS",
    "EXAMPLE_LINES",
    "JSON_SCHEMA_DIALECT",
    "OPEN_END",
    "REGISTRY_FILE_NAME",
    "SCHEMA_DESCRIPTION",
    "SCHEMA_TITLE",
    "TIMEZONE_CONTEXT_KEY",
    "TIME_TEXT_PATTERN",
    "AnySensorName",
    "BlankValue",
    "LocalTimeReader",
    "LocatedMapping",
    "LogEndTime",
    "LogTime",
    "OffSiteLog",
    "OffSiteLogError",
    "OffSiteLogFile",
    "OffSiteLogSettings",
    "OffSiteLogStore",
    "OffSitePeriod",
    "OffSiteReason",
    "StrictLogLoader",
    "build_json_schema",
    "format_local",
    "format_local_iso",
    "public_reason",
    "render_json_schema",
    "unknown_sensor_message",
]
