"""Mapping of quality-control events to the ``events/<sensor_id>.json`` entries of the site.

Quality control reports many event kinds (:class:`~sivin.quality.events.EventKind`); the site
publishes those worth a marker on the chart (``site.events``). Each published kind keeps its
string as the contract ``type``. Its *shape* decides the fields:

* **point** (``deployment``, ``retrieval``, ``step``, ``unconfirmed_transition``): ``type``,
  ``t``, ``source``, ``confidence``, ``detail``;
* **interval** (every other kind, e.g. ``off_site``, ``low_battery``, ``unlogged_off_site``):
  additionally ``t_end``, the end in Unix seconds, ``null`` while an ``off_site`` period is open.

The table is in ``docs/site.md``.

``detail`` is published through a per-kind filter (:data:`PUBLIC_DETAILS`): an ``off_site``
event carries only its reason category (``"service"``), never the free-text note of the
off-site log, by analogy with the owner decision of 2026-10-05 on registry notes. Kinds without
a filter publish their detail unchanged (texts generated by quality control).
"""

from __future__ import annotations

from collections.abc import Callable, Collection, Mapping
from typing import Final

from sivin.quality.events import EventKind, QualityEvent
from sivin.registry.offsite import public_reason
from sivin.site.columns import CONFIDENCE_DECIMALS, rounded_value, unix_second

POINT_KINDS: Final = frozenset(
    {
        EventKind.DEPLOYMENT,
        EventKind.RETRIEVAL,
        EventKind.STEP,
        EventKind.UNCONFIRMED_TRANSITION,
    }
)
"""Kinds published as point events (no ``t_end``); all others are intervals."""

DetailFilter = Callable[[str | None], str | None]
"""Turns an internal event ``detail`` into the published one (``None`` = no detail)."""

PUBLIC_DETAILS: Final[Mapping[EventKind, DetailFilter]] = {EventKind.OFF_SITE: public_reason}
"""Filters of the published ``detail`` per kind; other kinds publish their detail as is."""


class SiteEventMapping:
    """Turn QC events into contract entries, keeping only the published kinds.

    Parameters
    ----------
    published : collection of EventKind
        The kinds to publish (``site.events``).
    public_details : Mapping of EventKind to DetailFilter, optional
        Filters of the published ``detail``; :data:`PUBLIC_DETAILS` when omitted.
    """

    __slots__ = ("_details", "_published")

    def __init__(
        self,
        published: Collection[EventKind],
        public_details: Mapping[EventKind, DetailFilter] = PUBLIC_DETAILS,
    ) -> None:
        self._published = frozenset(published)
        self._details = dict(public_details)

    def entries(self, events: Collection[QualityEvent]) -> list[dict[str, object]]:
        """Return the entries of the published events, in the given (time) order.

        Parameters
        ----------
        events : collection of QualityEvent
            The QC events of one sensor.

        Returns
        -------
        list of dict
            One contract entry per published event.
        """
        return [self.entry(event) for event in events if event.kind in self._published]

    def entry(self, event: QualityEvent) -> dict[str, object]:
        """Return the contract entry of one event.

        Parameters
        ----------
        event : QualityEvent
            The event.

        Returns
        -------
        dict
            ``type``, ``t`` (Unix s), ``t_end`` (Unix s or ``null``, intervals only),
            ``source``, ``confidence`` (0-1 or ``null``), ``detail`` (public form).
        """
        entry: dict[str, object] = {"type": str(event.kind), "t": unix_second(event.t_utc)}
        if event.kind not in POINT_KINDS:
            entry["t_end"] = None if event.end_utc is None else unix_second(event.end_utc)
        entry["source"] = str(event.source)
        entry["confidence"] = rounded_value(event.confidence, CONFIDENCE_DECIMALS)
        detail = event.detail or None
        public = self._details.get(event.kind)
        entry["detail"] = detail if public is None else public(detail)
        return entry
