import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  parseDailyFile,
  parseEventsFile,
  parseIndicesFile,
  parseLatestFile,
  parseManifest,
  parseRawMonthFile,
  parseSensorsGeoJSON,
} from '../src/contract';
import { DataClient, type JsonFetcher } from '../src/data/DataClient';
import { QcMask } from '../src/domain/QcFlags';
import { utc } from './helpers';

/**
 * Cross-language contract test (WP-3.2): `fixtures/python-site/` is written by the Python
 * pipeline (`sivin run --skip-fetch`, regenerated with `.venv/bin/python -m tests.site.python_site`
 * in the repository root). Sensor 77799986 is the trimmed real export (public by owner decision),
 * sensor 77678271 is synthetic.
 */
const SITE_DIR = join(import.meta.dirname, 'fixtures', 'python-site');
const BASE = '/data/';
const REAL = '77799986';
const SYNTHETIC = '77678271';
const PRE_DEPLOYMENT = 32;

function files(directory: string): string[] {
  return readdirSync(directory).flatMap((name) => {
    const path = join(directory, name);
    return statSync(path).isDirectory() ? files(path) : [relative(SITE_DIR, path)];
  });
}

const fetcher: JsonFetcher = (url) => {
  const path = join(SITE_DIR, url.slice(BASE.length));
  const found = url.startsWith(BASE) && existsSync(path);
  return Promise.resolve({
    ok: found,
    status: found ? 200 : 404,
    json: () => Promise.resolve(JSON.parse(readFileSync(path, 'utf8')) as unknown),
  });
};

function json(path: string): unknown {
  return JSON.parse(readFileSync(join(SITE_DIR, path), 'utf8'));
}

type Parser = (value: unknown, file: string, warn: (message: string) => void) => unknown;

function parserFor(path: string): Parser {
  if (path === 'manifest.json') return (value, file, warn) => parseManifest(value, file, warn);
  if (path === 'latest.json') return (value, file) => parseLatestFile(value, file);
  if (path === 'sensors.geojson') return (value, file) => parseSensorsGeoJSON(value, file);
  if (path.startsWith('events/')) return parseEventsFile;
  if (path.startsWith('indices/')) return parseIndicesFile;
  if (path.endsWith('daily.json')) return parseDailyFile;
  return parseRawMonthFile;
}

describe('site data generated by the Python SiteBuilder', () => {
  const dataFiles = files(SITE_DIR).filter((path) => path !== 'README.md');

  it('has every kind of contract file', () => {
    expect(dataFiles).toContain('manifest.json');
    expect(dataFiles).toContain(`series/${SYNTHETIC}/raw/2026-05.json`);
    expect(dataFiles).toContain(`series/${REAL}/daily.json`);
    expect(dataFiles).toContain(`events/${REAL}.json`);
    expect(dataFiles).toContain('indices/2026.json');
  });

  it('validates every file without a contract error or warning', () => {
    const warnings: string[] = [];
    for (const path of dataFiles) {
      expect(() => parserFor(path)(json(path), path, (message) => warnings.push(message)), path).not.toThrow();
    }
    expect(warnings).toEqual([]);
  });

  it('loads through the DataClient with sensible values', async () => {
    const client = new DataClient(BASE, fetcher);
    const manifest = await client.getManifest();
    expect(manifest.schema_version).toBe(1);
    expect(Object.keys(manifest.sensors)).toEqual([SYNTHETIC, REAL]);
    expect(manifest.sensors[REAL]?.status).toBe('active');
    expect(manifest.sensors[REAL]?.data_status).toBeUndefined();
    expect(manifest.stale_after_s).toBe(129600);
    expect(manifest.variables.map((v) => v.id)).toEqual(['temp_c', 'rh_pct', 'precip_mm', 'battery_v']);
    expect(manifest.indices.find((index) => index.id === 'huglin')?.label.cs).toBe('Huglinův index');

    const registry = await client.getSensors();
    expect(registry.features.map((f) => f.properties.id)).toContain(REAL);

    const latest = await client.getLatest();
    // The real sensor was off site for the whole export, so it has no valid latest sample.
    expect(Object.keys(latest.sensors)).toEqual([SYNTHETIC]);
    expect(latest.sensors[SYNTHETIC]?.stale).toBe(true);

    for (const [id, entry] of Object.entries(manifest.sensors)) {
      const raw = await client.getRawRange(id, entry.first_t, entry.last_t + 1);
      expect(raw.t.length, id).toBeGreaterThan(0);
      expect(raw.t[0]).toBe(entry.first_t);
      expect(raw.t.at(-1)).toBe(entry.last_t);
      const daily = await client.getDaily(id);
      expect(daily.coverage.every((c) => c >= 0 && c <= 1)).toBe(true);
    }

    const synthetic = await client.getRawRange(SYNTHETIC, utc(2026, 5, 29), utc(2026, 6, 4));
    const temps = synthetic.temp_c.filter((v): v is number => v !== null);
    expect(Math.min(...temps)).toBeGreaterThanOrEqual(9);
    expect(Math.max(...temps)).toBeLessThanOrEqual(21);
    const mask = new QcMask();
    expect(synthetic.qc.every((flags) => !mask.excludes(flags))).toBe(true);

    const real = await client.getRawRange(REAL, utc(2025, 7, 1), utc(2026, 4, 1));
    expect(real.qc.every((flags) => (flags & PRE_DEPLOYMENT) !== 0)).toBe(true);

    const events = await client.getEvents(REAL);
    const offSite = events.events.find((event) => event.type === 'off_site');
    // Off-site log: 2025-07-30 10:00 CEST .. 2026-03-01 22:30 CET.
    expect(offSite).toMatchObject({ t: utc(2025, 7, 30, 8), t_end: utc(2026, 3, 1, 21, 30), source: 'log' });

    const indices = await client.getIndices(2026);
    const huglin = indices.sensors[SYNTHETIC]?.huglin;
    expect(huglin?.unit).toBe('°C·d');
    expect(huglin?.complete).toBe(false);
    expect(huglin?.estimated).toBe(false);
    expect(huglin?.class).toBeNull(); // no class for an incomplete result
    // The real sensor was off site the whole season: no value, no class, status no_data.
    const realEntries = Object.values(indices.sensors[REAL] ?? {});
    expect(realEntries.length).toBeGreaterThan(0);
    for (const entry of realEntries) {
      expect(entry).toMatchObject({ value: null, class: null, coverage: 0, status: 'no_data', detail: 'no data' });
    }
  });
});
