"""JSON schema and the Markdown key reference of the configuration.

Both include the registry-backed mappings: the settings of every registered quality check,
the parameters of every alignment strategy and of every climate index. ``sivin config schema``
prints them; the reference table of ``docs/configuration.md`` is generated by
:meth:`ConfigReference.markdown` (a test keeps it current).
"""

from __future__ import annotations

import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Any, Final, Literal

from pydantic import BaseModel
from pydantic.json_schema import models_json_schema

from sivin.config.model import SivinConfig
from sivin.config.registered import RegisteredSettings, default_resolutions
from sivin.config.sections import TimeConfig
from sivin.config.shared import SharedValues, settings_model_of

DEFS: Final = "$defs"
"""Key of the shared definitions in a JSON schema."""

SCHEMA_MODE: Final[Literal["validation"]] = "validation"
"""Pydantic JSON schema mode: the schema of the input (the YAML file)."""


class ConfigSchema:
    """The JSON schema of ``config/sivin.yaml`` with the registered settings filled in.

    Parameters
    ----------
    resolutions : sequence of RegisteredSettings, optional
        The registry-backed mappings; :func:`~sivin.config.registered.default_resolutions`
        when omitted.
    """

    __slots__ = ("_resolutions",)

    def __init__(self, resolutions: Sequence[RegisteredSettings] | None = None) -> None:
        self._resolutions = tuple(resolutions if resolutions is not None else default_resolutions())

    def json_schema(self) -> dict[str, Any]:
        """Return the JSON schema (draft 2020-12, as generated by pydantic).

        Returns
        -------
        dict
            Schema of :class:`~sivin.config.model.SivinConfig`; ``quality.check_settings``
            and ``analytics.indices`` list one property per registered name,
            ``alignment.params`` is one of the strategies' parameter schemas.
        """
        registered = [model for resolution in self._resolutions for _, model in resolution.models()]
        models: list[type[BaseModel]] = [SivinConfig, *dict.fromkeys(registered)]
        refs, schema = models_json_schema(
            [(model, SCHEMA_MODE) for model in models], title=SivinConfig.__name__
        )
        definitions: dict[str, Any] = schema[DEFS]
        root = _definition(definitions, refs[(SivinConfig, SCHEMA_MODE)])
        for resolution in self._resolutions:
            owner = _owner_definition(definitions, root, resolution.location)
            leaf = resolution.location[-1]
            described = owner["properties"][leaf].get("description", "")
            references = {name: refs[(model, SCHEMA_MODE)] for name, model in resolution.models()}
            if resolution.keyed:
                owner["properties"][leaf] = {
                    "description": described,
                    "type": "object",
                    "properties": references,
                    "additionalProperties": False,
                }
            else:
                owner["properties"][leaf] = {
                    "description": described,
                    "anyOf": list(references.values()),
                }
        return {**root, DEFS: {k: v for k, v in definitions.items() if v is not root}}

    def text(self) -> str:
        """Return the JSON schema as indented JSON text.

        Returns
        -------
        str
            Two-space indented JSON, keys in model order, ending with a line break.
        """
        return json.dumps(self.json_schema(), indent=2, ensure_ascii=False) + "\n"


def _definition(definitions: Mapping[str, Any], reference: Mapping[str, Any]) -> dict[str, Any]:
    """Return the definition a ``{"$ref": "#/$defs/<Name>"}`` points to."""
    name = str(reference["$ref"]).rsplit("/", 1)[-1]
    found: dict[str, Any] = definitions[name]
    return found


def _owner_definition(
    definitions: Mapping[str, Any], root: dict[str, Any], location: tuple[str, ...]
) -> dict[str, Any]:
    """Return the schema definition of the model that holds the field at ``location``.

    The sections on the way are plain model fields, so each property is a direct ``$ref``.
    """
    owner = root
    for key in location[:-1]:
        owner = _definition(definitions, owner["properties"][key])
    return owner


@dataclass(frozen=True, slots=True)
class ReferenceRow:
    """One key of the configuration in the reference table.

    Attributes
    ----------
    path : str
        Key path, e.g. ``quality.check_settings.range.temp_climate_max_c``.
    default : str
        Default value as JSON, or the ``time`` key it is set from.
    description : str
        The field description (with its unit and the origin of the default).
    """

    path: str
    default: str
    description: str


class ConfigReference:
    """Every key of ``config/sivin.yaml`` with its default and description.

    Parameters
    ----------
    resolutions : sequence of RegisteredSettings, optional
        The registry-backed mappings; :func:`~sivin.config.registered.default_resolutions`
        when omitted.
    """

    __slots__ = ("_defaults", "_resolutions", "_shared")

    def __init__(self, resolutions: Sequence[RegisteredSettings] | None = None) -> None:
        self._resolutions = tuple(resolutions if resolutions is not None else default_resolutions())
        self._shared = SharedValues.from_time(TimeConfig())
        self._defaults = SivinConfig().model_dump(mode="json", by_alias=True)

    def rows(self) -> list[ReferenceRow]:
        """Return one row per configuration key, in model order.

        Returns
        -------
        list of ReferenceRow
            Section by section; registered settings follow their mapping key, e.g.
            ``analytics.indices.<index_id>.<parameter>``.
        """
        rows: list[ReferenceRow] = []
        self._walk(SivinConfig, self._defaults, (), rows)
        return rows

    def markdown(self) -> str:
        """Return the reference as Markdown tables, one per top-level section.

        Returns
        -------
        str
            ``### <section>`` headings, each followed by a ``| Key | Default | Description |``
            table; ends with a line break.
        """
        lines: list[str] = []
        section = None
        for row in self.rows():
            top = row.path.split(".", 1)[0]
            if top != section:
                section = top
                lines += [
                    "",
                    f"### `{top}`",
                    "",
                    "| Key | Default | Description |",
                    "|---|---|---|",
                ]
            lines.append(f"| `{row.path}` | {_cell(row.default)} | {_cell(row.description)} |")
        return "\n".join(lines).lstrip("\n") + "\n"

    def _walk(
        self,
        model: type[BaseModel],
        defaults: object,
        path: tuple[str, ...],
        rows: list[ReferenceRow],
    ) -> None:
        values = defaults if isinstance(defaults, Mapping) else {}
        for name, info in model.model_fields.items():
            key = info.alias or name
            location = (*path, key)
            registered = self._registered(location)
            nested = settings_model_of(info.annotation)
            value = values.get(key)
            if registered is not None:
                self._walk_registered(registered, value, location, rows)
            elif nested is not None and isinstance(value, Mapping):
                self._walk(nested, value, location, rows)
            else:
                rows.append(
                    ReferenceRow(
                        ".".join(location),
                        self._default_text(name, location, value),
                        info.description or "",
                    )
                )

    def _walk_registered(
        self,
        resolution: RegisteredSettings,
        value: object,
        location: tuple[str, ...],
        rows: list[ReferenceRow],
    ) -> None:
        values = value if isinstance(value, Mapping) else {}
        for name, model in resolution.models():
            if resolution.keyed:
                defaults = values.get(name, model().model_dump(mode="json", by_alias=True))
                self._walk(model, defaults, (*location, name), rows)
            else:
                prefix = f"{'.'.join(location)} ({name})"
                own: list[ReferenceRow] = []
                self._walk(model, model().model_dump(mode="json", by_alias=True), (), own)
                rows.extend(
                    ReferenceRow(f"{prefix}.{row.path}", row.default, row.description)
                    for row in own
                )

    def _registered(self, location: tuple[str, ...]) -> RegisteredSettings | None:
        for resolution in self._resolutions:
            if resolution.location == location:
                return resolution
        return None

    def _default_text(self, name: str, location: tuple[str, ...], value: object) -> str:
        shared = next(
            (
                item
                for item in self._shared.values
                if name in item.field_names and location[0] != "time"
            ),
            None,
        )
        if shared is not None:
            return f"= `{shared.origin}`"
        return f"`{json.dumps(value, ensure_ascii=False)}`"


def _cell(text: str) -> str:
    """Escape a text for a Markdown table cell."""
    return text.replace("|", "\\|").replace("\n", " ")
