"""The site data the web's cross-language contract test reads (``web/tests/fixtures/python-site``).

``sivin run --skip-fetch`` in a temporary project with the repository's registry and off-site
log, the trimmed **REAL** export of sensor 77799986 (public by owner decision 2026-10-05; off
site for the whole export) and a **SYNTHETIC** 4-day export of sensor 77678271 across the
May/June 2026 month boundary. The fixture is committed; ``tests/e2e/test_site.py`` checks that
it is up to date. Regenerate after a change of the output with::

    .venv/bin/python -m tests.site.python_site
"""

from __future__ import annotations

import contextlib
import shutil
import tempfile
from datetime import UTC, datetime
from pathlib import Path
from typing import Final

from tests.app.project import REPO_ROOT, make_project, write_synthetic_export
from typer.testing import CliRunner

from sivin.cli import main as cli
from sivin.cli.state import CliOverrides
from sivin.site.state import STATE_FILE

FIXTURE_DIR: Final = REPO_ROOT / "web" / "tests" / "fixtures" / "python-site"
"""The committed fixture."""

FIXTURE_README: Final = "README.md"
"""The fixture's description (not produced by the builder)."""

RUN_TIME: Final = datetime(2026, 10, 5, 4, 0, tzinfo=UTC)
"""Fixed ``generated_at`` of the fixture (06:00 local time, the daily run)."""

SYNTHETIC_START: Final = datetime(2026, 5, 30, 0, 0, 10)
"""First local time of the synthetic export of 77678271."""

SYNTHETIC_DAYS: Final = 4

README_TEXT: Final = """\
# Site data generated by the Python pipeline — test fixture

Generated by `tests/site/python_site.py` (`.venv/bin/python -m tests.site.python_site`):
`sivin run --skip-fetch` in a temporary project, `generated_at` fixed to
2026-10-05T04:00:00Z. Do not edit by hand; `tests/e2e/test_site.py` fails when it is stale.

- Sensor **77799986**: the trimmed **real** export (300 rows, 2025-07-30 .. 2026-03-01; public by
  owner decision 2026-10-05). The sensor was off site the whole time (off-site log), so every
  sample is flagged `PRE_DEPLOYMENT` (32).
- Sensor **77678271**: **SYNTHETIC** data (4 days from 2026-05-30, daily cycle 15 ± 6 °C) —
  invented numbers, not measurements.

`web/tests/pythonSite.test.ts` reads every file through the web's validators and `DataClient`.
"""


def build_site(workdir: Path, overrides: CliOverrides | None = None) -> Path:
    """Run ``sivin run --skip-fetch`` in a new project below ``workdir``.

    Parameters
    ----------
    workdir : pathlib.Path
        An empty directory.
    overrides : CliOverrides, optional
        Collaborators of the CLI; a fixed clock when omitted.

    Returns
    -------
    pathlib.Path
        The generated ``site/data`` directory.
    """
    project = make_project(workdir / "vineyard")
    project.real_export()
    write_synthetic_export(project.downloads, start_local=SYNTHETIC_START, days=SYNTHETIC_DAYS)
    given = overrides if overrides is not None else CliOverrides(clock=lambda: RUN_TIME)
    with contextlib.chdir(project.root):
        result = CliRunner().invoke(cli.app, ["run", "--skip-fetch"], obj=given)
    if result.exit_code != 0:
        raise RuntimeError(f"sivin run failed ({result.exit_code}):\n{result.output}")
    return project.root / "site" / "data"


def contract_files(root: Path) -> dict[str, bytes]:
    """Return the contract files below ``root`` (no build state, no README).

    Parameters
    ----------
    root : pathlib.Path
        A site data directory.

    Returns
    -------
    dict of str to bytes
        Relative path → content.
    """
    return {
        path.relative_to(root).as_posix(): path.read_bytes()
        for path in sorted(root.rglob("*"))
        if path.is_file() and path.name not in (STATE_FILE, FIXTURE_README)
    }


def write_fixture(files: dict[str, bytes], target: Path) -> None:
    """Replace the fixture directory with ``files`` and the README.

    Parameters
    ----------
    files : dict of str to bytes
        Relative path → content.
    target : pathlib.Path
        The fixture directory.
    """
    if target.exists():
        shutil.rmtree(target)
    for relative, content in files.items():
        path = target / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
    (target / FIXTURE_README).write_text(README_TEXT, encoding="utf-8")


def main() -> None:
    """Regenerate :data:`FIXTURE_DIR`."""
    with tempfile.TemporaryDirectory() as workdir:
        write_fixture(contract_files(build_site(Path(workdir))), FIXTURE_DIR)


if __name__ == "__main__":
    main()
